### ISSUE TITLE
Dir clone configuration

### ISSUE THREAD

**Issue by greyshaman** [greyshaman/rfs_tester#10]
It would be helpful if the configuration allowed me to specify the path of the directory from which all files and folders should be copied to the temporary folder.

**Comment by greyshaman** [comment]
Starting with version 1.1.0, we have added a new configuration option that allows users to easily create a copy of an existing directory for testing purposes. This new feature, called "clone_directory", takes two parameters: "name", which specifies the name of the copy, and "source", which is the path to the original directory. The "clone_directory" command creates a new sandbox directory with all the files and folders from the specified source directory.

simple yaml example:

```yaml
- !clone_directory
       name: test_yaml_config_with_clone_directory
       source: src
```

Sandbox configuration can start from clone_directory configuration entry.
